name: Deploy to Firebase Hosting and Functions
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies (Frontend)
        run: bun install

      - name: Install Dependencies (Functions)
        run: npm ci 
        working-directory: ./functions

      - name: Compile and Validate Firebase Rules
        run: ./scripts/validate-rules.sh

      - name: Build Frontend
        run: bun run build
        env:
          CI: true
          VITE_FIREBASE_URL: ${{ secrets.VITE_FIREBASE_URL }}
          VITE_FIREBASE_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_BUCKET: ${{ secrets.VITE_FIREBASE_BUCKET }}
          VITE_APP_TITLE: "TreesRadio"

      - name: Build Functions
        run: npm run build
        working-directory: ./functions

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIVE }}'
          channelId: live
          projectId: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          expires: 7d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Deploy Firebase Functions, Database Rules, and Storage Rules
        run: |
          echo "Project ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}"
          # Strip newlines from project_id ugh
          export VITE_FIREBASE_PROJECT_ID=$(echo ${{ secrets.VITE_FIREBASE_PROJECT_ID }} | tr -d '\n')
          echo "Project ID: $VITE_FIREBASE_PROJECT_ID"
          npx firebase-tools deploy --only functions,database,storage --project "${VITE_FIREBASE_PROJECT_ID}" --token "${{ secrets.FIREBASE_CLI_TOKEN }}"
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Apply Storage CORS Configuration
        run: |
          export VITE_FIREBASE_PROJECT_ID=$(echo ${{ secrets.VITE_FIREBASE_PROJECT_ID }} | tr -d '\n')
          ./scripts/apply-cors.sh "${VITE_FIREBASE_PROJECT_ID}"
        continue-on-error: true  # Don't fail the build if CORS setup fails
        